# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeidentity
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - service-frontend.yaml
  - service-backend.yaml
  - deployment-frontend.yaml
  - deployment-backend.yaml